apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: hlzax11sh-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hlzax11sh-python 
  name: hlzax11sh-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: hlzax11sh-python 
